---
- name: Update pip
  pip: name=pip state=latest extra_args='--upgrade'

- name: Install virtualenv
  pip: name=virtualenv state=present

- name: Install virtualenv wrapper
  pip: name=virtualenvwrapper state=present
