---
- name: Update the user gems
  shell: gem update

- name: Install bundler
  gem: name=bundler state=present

- name: Install rake
  gem: name=rake state=present

- name: Install hobo
  gem: name=hobo-inviqa state=present

- name: Rehash rbenv
  shell: rbenv rehash
